### ISSUE TITLE
Tabs - add a "Market" tab

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#11]
Suggest a "Market" also be added so that the market action can be monitored.  Assume possibility that errors in the market are not picked up in the admin view.

**Comment by ArtemShatalov** [comment]
@wisdomcsharp,

Is Invoices page not enough? Assumed that Administrator can select only invoices with Auction open status. Hence, he'll have almost all information that Market contains (except Return, which, I think, not essential)

**Comment by wisdomcsharp** [comment]
In the invoices section, when view is clicked per/invoice, which just need to list bids. So the administrator can "view" participants.

**Comment by ArtemShatalov** [comment]
Yes. And this list supposed to be there. Invoice details view for administrator is as the same as for users

![image](https://user-images.githubusercontent.com/12482899/37698670-86db51ee-2cec-11e8-9855-a06631f49f22.png)
