### ISSUE TITLE
Master Switch

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#15]
Suggestion - Include master switches for enable/disable of various functions

Enable/disable - all accounts - viewing of account possible but not permitted to placed bids
Enable/disable - all PPT withdrawals
Enable/disable - all Poken withdrawals

Currently don't see any enable/disable features implement yet.  However, enable/disable buttons should also be applied to individual users.  See #3 and #4 also where suggested.

**Comment by wisdomcsharp** [comment]
ignore. falls under maintenance category.
