### ISSUE TITLE
Currencies - Originally entered text does not erase

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#27]
![currencies clear previous entry](https://user-images.githubusercontent.com/31194353/37552431-2874823c-29f0-11e8-9109-a958eb188f87.png)

**Comment by topd333** [comment]
https://github.com/bitpopulous/platform-admin/issues/290

**Comment by wisdomcsharp** [comment]
Note: should only be cleared, when "create currency token" is clicked.
