### ISSUE TITLE
Admin Login Page - change style and delete all reference to Populous

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#37]
Suggest to keep the admin log in page as simple as possible.  Just a place to type in email, password and login button is sufficient.

Remove all items that identify the log in page with Populous.  The style of the log in feature should also be different to main Populous login to avoid it being easily identifiable as Populous admin.  

Any identifiers on the page will make it easy to identify that it is a part of Populous.  No need to make it easy for people seeking to find Populous websites to hack.

![admin login page](https://user-images.githubusercontent.com/31194353/37561045-6955da50-2a7f-11e8-9290-f09858333489.png)

**Comment by wisdomcsharp** [comment]
-ignore.
Admins can only access this page whilst inside populous offices on our local intranet.
