### ISSUE TITLE
Currencies - do not allow circulation of Pokens in borrower/investor wallets when amount is 0 (zero)

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#39]
![cuurencies - create mint zero amount](https://user-images.githubusercontent.com/31194353/37561700-5c66e292-2a90-11e8-8b2e-3aed1ce2eafc.png)

Issue raised applicable to borrower/investor login review.  Criteria can be set on both side.

The increase in number of coins makes the list longer and hence page scroll longer to transaction history.  Issue raised in issue community_reviews https://github.com/bitpopulous/community_reviews/issues/536

**Comment by wisdomcsharp** [comment]
- This shows the balance of populous, mainly from platform fees.
