### ISSUE TITLE
Upload Gold Document - More details should be provided

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#43]
The upload of document requested only to document the Gold.  Suggest to also enter other gold data related information that can then be used.  The entry process would be similar to "Invoice Approval Checklist" as per issue #10.

![upload gold document](https://user-images.githubusercontent.com/31194353/37580828-b8009508-2b80-11e8-9340-e97846d1da5d.png)

**Comment by wisdomcsharp** [comment]
-ignore, total amount audited, further details stored with gold suppliers/brokers
