### ISSUE TITLE
User Details - Invoice Transaction - Borrower

### ISSUE THREAD

**Issue by PeterWong1** [bitpopulous/admin_reviews#6]
Suggest to list all individual invoice and transfer funds for each respective invoice.  Easier to reconcile.  Can also be shared in front-end with user as down load summary etc....

![4d admin user details - borrower - invoices](https://user-images.githubusercontent.com/31194353/37547981-d7081854-29af-11e8-985a-a8354e2409af.png)

**Comment by PeterWong1** [comment]
As an alternative solution, all individual records are kept here for ease of reference.  The transfer of funds can be performed under dedicated tab "Deposit/Withdrawal" as per raised under issue #40.

**Comment by wisdomcsharp** [comment]
Transfer funds (adding payments towards invoices, from the buyer), essentially goes through and makes a payment to every invoice opened by the buyer, if there's enough funds. there's no need to credit each invoice manually.
